# Generated by Django 2.2.2 on 2020-06-10 10:16

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200610_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=account.models.upload_location),
        ),
    ]
