# Generated by Django 2.2.2 on 2020-06-30 18:55

import account.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200610_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[300, 300], upload_to=account.models.upload_location),
        ),
    ]
