# Generated by Django 2.2.2 on 2020-06-30 19:00

import account.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200630_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, size=[3000, 3000], upload_to=account.models.upload_location),
        ),
    ]
