# Generated by Django 2.2.2 on 2020-06-30 19:02

import account.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200630_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[100, 100], upload_to=account.models.upload_location),
        ),
    ]
