# Generated by Django 2.2.2 on 2020-06-30 19:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200630_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=account.models.upload_location),
        ),
    ]
