# Generated by Django 2.2.14 on 2020-07-14 19:13

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200630_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='account/img/default.jpg', upload_to=account.models.upload_location),
        ),
    ]
