# Generated by Django 2.2.2 on 2020-06-16 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='post',
            name='heart',
            field=models.ManyToManyField(blank=True, related_name='heart', to=settings.AUTH_USER_MODEL),
        ),
    ]
